/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controler.Ctr_Clientes;
import Controler.Ctr_Pagamentos;
import Controler.Ctr_Quartos;
import Model.Clientes;
import Model.Pagamentos;
import Model.Quartos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author arauj
 */
public class Form_Pagamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form Form_Pagamentos
     */
    public Form_Pagamentos() {
        initComponents();
        readTb_ListaClientes();
        readTb_ListaQuartos();
        readTb_ListaPagamentos();
        txt_cliente.setEditable(false);
        txt_quarto.setEditable(false);
        txt_diaria.setEditable(false);
     }
    
    public void readTb_ListaClientes(){
        DefaultTableModel modelo = (DefaultTableModel)tb_listaClientes.getModel();
        modelo.setNumRows(0);
        Ctr_Clientes controle = new Ctr_Clientes();   
     
        for(Clientes c: controle.selecionarTodos()){
            modelo.addRow(new Object[]{      
            c.getId_cliente(),
            c.getNome(),
            c.getCpf(),
            c.getTelefone(),
            c.getEmail(),
            c.getRua(),
            c.getNumero_casa(),
            c.getBairro(),
            });
        }
    }
    
    public void readTb_ListaQuartos(){
        DefaultTableModel modelo = (DefaultTableModel)tb_listaQuartos.getModel();
        modelo.setNumRows(0);
        Ctr_Quartos controle = new Ctr_Quartos();   
     
        for(Quartos q: controle.selecionarTodos()){
            modelo.addRow(new Object[]{      
            q.getIdquartos(),
            q.getNumero(),
            q.getAndar(),
            q.getDescricao(),
            q.getCaracteristicas(),
            q.getValorDiaria(),
            q.getEstado(),
            q.getTipoQuarto()});
        }
    }
    
    public void readTb_ListaPagamentos(){
        DefaultTableModel modelo = (DefaultTableModel)tb_listaPagamentos.getModel();
        modelo.setNumRows(0);
        Ctr_Pagamentos controle = new Ctr_Pagamentos();   
     
        for(Pagamentos p: controle.selecionarTodos()){
            modelo.addRow(new Object[]{      
            p.getId_pagamento(),
            p.getCliente(),
            p.getQuarto(),
            p.getDias_hospedado(),
            p.getTotal_cobrado(),
            });
        }
    }
    
    public void buscaFeitaPagamentos(String busca){
        DefaultTableModel modelo = (DefaultTableModel)tb_listaPagamentos.getModel();
        modelo.setNumRows(0);
        Ctr_Pagamentos controle = new Ctr_Pagamentos();   
     
        for(Pagamentos p: controle.buscar(busca)){
            modelo.addRow(new Object[]{      
            p.getId_pagamento(),
            p.getCliente(),
            p.getQuarto(),
            p.getDias_hospedado(),
            p.getTotal_cobrado(),
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_listaPagamentos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txt_pesquisarPagamentos = new javax.swing.JTextField();
        btnBuscarPagamentos = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_dias_hospedado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txt_cliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_quarto = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_diaria = new javax.swing.JTextField();
        btnGerarPDF = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_listaClientes = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_listaQuartos = new javax.swing.JTable();

        tb_listaPagamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Cliente", "Quarto", "Dias Hospedado", "Total Cobrado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_listaPagamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listaPagamentosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_listaPagamentos);

        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Pesquisar");

        btnBuscarPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_search_black_18dp.png"))); // NOI18N
        btnBuscarPagamentos.setText("Buscar");
        btnBuscarPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPagamentosActionPerformed(evt);
            }
        });

        btnApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_delete_black_18dp.png"))); // NOI18N
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_exit_to_app_black_18dp.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel14.setText("Lista dos Pagamentos");

        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Dias Hospedados");

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_save_alt_black_18dp.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Cliente");

        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Quarto");

        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Diaria");

        btnGerarPDF.setText("Gerar Relatorio");
        btnGerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(10, 10, 10)
                                .addComponent(txt_pesquisarPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel14)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(10, 10, 10)
                                .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20)
                                .addGap(10, 10, 10)
                                .addComponent(txt_quarto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(10, 10, 10)
                                .addComponent(txt_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(10, 10, 10)
                                .addComponent(txt_dias_hospedado, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(btnGerarPDF)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txt_quarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txt_diaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_pesquisarPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarPagamentos)
                        .addComponent(btnApagar)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSair)
                        .addComponent(txt_dias_hospedado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerarPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tb_listaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nome", "CPF", "Telefone", "Email", "Rua", "Numero", "Bairro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_listaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listaClientesMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tb_listaClientes);

        jLabel16.setText("Lista de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel12.setText("Lista de Quartos");

        tb_listaQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Número", "Andar", "Descrição", "Caracteristicas", "Diaria", "Estado", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_listaQuartos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_listaQuartosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tb_listaQuartos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(486, 486, 486))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_listaPagamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listaPagamentosMouseClicked
      //Não necessario
    }//GEN-LAST:event_tb_listaPagamentosMouseClicked

    private void btnBuscarPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPagamentosActionPerformed
        String busca = txt_pesquisarPagamentos.getText();
        if(busca.isEmpty()){
            readTb_ListaPagamentos();
        }else{
            buscaFeitaPagamentos(busca);
        }
    }//GEN-LAST:event_btnBuscarPagamentosActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int id_pagamento =  (int) tb_listaPagamentos.getValueAt(tb_listaPagamentos.getSelectedRow(),0);
        Ctr_Pagamentos Ctrpagamentos = new Ctr_Pagamentos();
        Ctrpagamentos.deletar(id_pagamento);
        ((DefaultTableModel) tb_listaPagamentos.getModel()).removeRow(tb_listaPagamentos.getSelectedRow());
        
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void tb_listaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listaClientesMouseClicked
        if(tb_listaClientes.getSelectedRow() != -1){
            txt_cliente.setText(tb_listaClientes.getValueAt(tb_listaClientes.getSelectedRow(), 1).toString());
        }
    }//GEN-LAST:event_tb_listaClientesMouseClicked

    private void tb_listaQuartosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_listaQuartosMouseClicked
        if(tb_listaQuartos.getSelectedRow() != -1){
          txt_quarto.setText(tb_listaQuartos.getValueAt(tb_listaQuartos.getSelectedRow(), 1).toString());
          txt_diaria.setText(tb_listaQuartos.getValueAt(tb_listaQuartos.getSelectedRow(), 5).toString());
        }
    }//GEN-LAST:event_tb_listaQuartosMouseClicked

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Pagamentos pagamento = new Pagamentos();
        Ctr_Pagamentos ctrPagamentos = new Ctr_Pagamentos();
        
        String cliente = txt_cliente.getText();
        String quarto = txt_quarto.getText();
        int diasHospedado = Integer.parseInt(txt_dias_hospedado.getText());
        double diaria = Double.parseDouble(txt_diaria.getText());
        double totalCobrado = (diasHospedado  * diaria);

        pagamento = new Pagamentos(cliente,quarto,diasHospedado,totalCobrado,diaria);
        ctrPagamentos.inserir(pagamento);
        readTb_ListaPagamentos();
        limparCampos();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnGerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPDFActionPerformed
        Ctr_Pagamentos pagamento = new Ctr_Pagamentos();
        pagamento.gerarPDF();
    }//GEN-LAST:event_btnGerarPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnBuscarPagamentos;
    private javax.swing.JButton btnGerarPDF;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tb_listaClientes;
    private javax.swing.JTable tb_listaPagamentos;
    private javax.swing.JTable tb_listaQuartos;
    private javax.swing.JTextField txt_cliente;
    private javax.swing.JTextField txt_diaria;
    private javax.swing.JTextField txt_dias_hospedado;
    private javax.swing.JTextField txt_pesquisarPagamentos;
    private javax.swing.JTextField txt_quarto;
    // End of variables declaration//GEN-END:variables
public void limparCampos(){
    txt_cliente.setText("");
    txt_quarto.setText("");
    txt_dias_hospedado.setText("");
    txt_diaria.setText("");
}
}
