/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author arauj
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_funcionario = new javax.swing.JMenuItem();
        menu_quartos = new javax.swing.JMenu();
        acessar_quartos = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_Clientes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_produtos = new javax.swing.JMenuItem();
        menu_pagamentos = new javax.swing.JMenu();
        menu_pagamento = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 927, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jMenuBar1.setPreferredSize(new java.awt.Dimension(421, 30));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_person_black_18dp.png"))); // NOI18N
        jMenu1.setText("Funcionarios");

        menu_funcionario.setText("Acessar");
        menu_funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_funcionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menu_funcionario);

        jMenuBar1.add(jMenu1);

        menu_quartos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_home_black_18dp.png"))); // NOI18N
        menu_quartos.setText("Quartos");
        menu_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_quartosActionPerformed(evt);
            }
        });

        acessar_quartos.setText("Acessar");
        acessar_quartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acessar_quartosActionPerformed(evt);
            }
        });
        menu_quartos.add(acessar_quartos);

        jMenuBar1.add(menu_quartos);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_face_black_18dp.png"))); // NOI18N
        jMenu3.setText("Clientes");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        menu_Clientes.setText("Acessar");
        menu_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ClientesActionPerformed(evt);
            }
        });
        jMenu3.add(menu_Clientes);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_restaurant_black_18dp.png"))); // NOI18N
        jMenu4.setText("Produtos");

        menu_produtos.setText("Acessar");
        menu_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_produtosActionPerformed(evt);
            }
        });
        jMenu4.add(menu_produtos);

        jMenuBar1.add(jMenu4);

        menu_pagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/icons/baseline_payment_black_18dp.png"))); // NOI18N
        menu_pagamentos.setText("Pagamentos");

        menu_pagamento.setText("Acessar");
        menu_pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pagamentoActionPerformed(evt);
            }
        });
        menu_pagamentos.add(menu_pagamento);

        jMenuBar1.add(menu_pagamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_quartosActionPerformed
        
    }//GEN-LAST:event_menu_quartosActionPerformed

    private void acessar_quartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acessar_quartosActionPerformed
        Form_Quartos quartos = new Form_Quartos();
        quartos.setSize(910,535);
        quartos.setVisible(true);
        jdpPrincipal.add(quartos);
    }//GEN-LAST:event_acessar_quartosActionPerformed

    private void menu_funcionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_funcionarioActionPerformed
        Form_Funcionarios funcionario = new Form_Funcionarios();
        funcionario.setSize(970, 400);
        funcionario.setVisible(true);
        jdpPrincipal.add(funcionario);
    }//GEN-LAST:event_menu_funcionarioActionPerformed

    private void menu_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ClientesActionPerformed
        Form_Clientes clientes = new Form_Clientes();
        clientes.setSize(970, 400);
        clientes.setVisible(true);
        jdpPrincipal.add(clientes);
    }//GEN-LAST:event_menu_ClientesActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void menu_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_produtosActionPerformed
        Form_Produtos produtos = new Form_Produtos();
        produtos.setSize(970, 400);
        produtos.setVisible(true);
        jdpPrincipal.add(produtos);
    }//GEN-LAST:event_menu_produtosActionPerformed

    private void menu_pagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pagamentoActionPerformed
        Form_Pagamentos pagamentos = new Form_Pagamentos();
        pagamentos.setSize(1011, 606);
        pagamentos.setVisible(true);
        jdpPrincipal.add(pagamentos);
    }//GEN-LAST:event_menu_pagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acessar_quartos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem menu_Clientes;
    private javax.swing.JMenuItem menu_funcionario;
    private javax.swing.JMenuItem menu_pagamento;
    private javax.swing.JMenu menu_pagamentos;
    private javax.swing.JMenuItem menu_produtos;
    private javax.swing.JMenu menu_quartos;
    // End of variables declaration//GEN-END:variables
}
