-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 15:01:51 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BancoHoteleiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BancoHoteleiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BancoHoteleiro` DEFAULT CHARACTER SET utf8 ;
USE `BancoHoteleiro` ;

-- -----------------------------------------------------
-- Table `BancoHoteleiro`.`tb_quartos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoHoteleiro`.`tb_quartos` (
  `id_quartos` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `andar` VARCHAR(3) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `caracteristicas` VARCHAR(350) NULL,
  `preco_diaria` DECIMAL(7,2) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `tipo_quarto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_quartos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoHoteleiro`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoHoteleiro`.`tb_clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `rua` VARCHAR(100) NULL,
  `numero_casa` VARCHAR(20) NULL,
  `bairro` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoHoteleiro`.`tb_funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoHoteleiro`.`tb_funcionarios` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(20) NOT NULL,
  `rua` VARCHAR(100) NULL,
  `numero_casa` VARCHAR(10) NULL,
  `bairro` VARCHAR(100) NULL,
  `num_car_trab` VARCHAR(20) NOT NULL,
  `data_nascimento` VARCHAR(20) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `data_entrada` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoHoteleiro`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoHoteleiro`.`tb_produtos` (
  `id_produtos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `quantidade` INT NOT NULL,
  `preco_uni` DECIMAL(7,2) NOT NULL,
  `observacao` VARCHAR(100) NULL,
  PRIMARY KEY (`id_produtos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoHoteleiro`.`tb_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoHoteleiro`.`tb_pagamentos` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(45) NULL,
  `quarto` VARCHAR(45) NULL,
  `dias_hospedado` INT NOT NULL,
  `total_cobrado` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BancoHoteleiro`.`tb_checkin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BancoHoteleiro`.`tb_checkin` (
  `id_Checkin` INT NOT NULL AUTO_INCREMENT,
  `id_quarto` INT NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cpf` VARCHAR(50) NOT NULL,
  `telefone` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero_casa` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `data_entrada` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Checkin`),
  INDEX `FKcheck_quarto_idx` (`id_quarto` ASC),
  CONSTRAINT `FKcheck_quarto`
    FOREIGN KEY (`id_quarto`)
    REFERENCES `BancoHoteleiro`.`tb_quartos` (`id_quartos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
